apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sites-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/gitops-repo.git' # GitOps repository URL
    targetRevision: main                                  # Branch or tag to pull from
    path: applicationsets/sites.yaml       # Path to the sites ApplicationSet YAML in the repository
  destination:
    server: https://kubernetes.default.svc               # Default ArgoCD destination server
    namespace: argocd                                    # ArgoCD namespace
  syncPolicy:
    automated:
      prune: true                                        # Remove out-of-sync resources
      selfHeal: true                                     # Automatically sync resources if they drift